services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQl\Translations\Service\LocaleServiceInterface:
    class: OxidEsales\GraphQl\Translations\Service\LocaleService

  OxidEsales\GraphQl\Translations\Type\ObjectType\LocaleType:
    class: OxidEsales\GraphQl\Translations\Type\ObjectType\LocaleType

  OxidEsales\GraphQl\Translations\Type\Provider\LocaleProvider:
    class: OxidEsales\GraphQl\Translations\Type\Provider\LocaleProvider
    tags: ['graphql_query_provider']

  OxidEsales\GraphQl\Sample\Service\PermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    calls:
      - ['addPermission', ['admin', 'maywritetranslationo']]
      - ['addPermission', ['shopadmin', 'maywritetranslation']]
    tags: ['graphql_permissions_provider']
