services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQl\Translations\Service\LanguageServiceInterface:
    class: OxidEsales\GraphQl\Translations\Service\LanguageService

  OxidEsales\GraphQl\Translations\Service\TranslationServiceInterface:
    class: OxidEsales\GraphQl\Translations\Service\TranslationService

  OxidEsales\GraphQl\Translations\Type\ObjectType\LanguageType:
    class: OxidEsales\GraphQl\Translations\Type\ObjectType\LanguageType

  OxidEsales\GraphQl\Translations\Type\Provider\LanguageProvider:
    class: OxidEsales\GraphQl\Translations\Type\Provider\LanguageProvider
    tags: ['graphql_query_provider']

  OxidEsales\GraphQl\Translations\Type\ObjectType\TranslationType:
    class: OxidEsales\GraphQl\Translations\Type\ObjectType\TranslationType

  OxidEsales\GraphQl\Translations\Type\Provider\TranslationProvider:
    class: OxidEsales\GraphQl\Translations\Type\Provider\TranslationProvider
    tags: ['graphql_query_provider','graphql_mutation_provider']

  OxidEsales\GraphQl\Service\PermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    calls:
      - ['addPermission', ['admin', 'maywritetranslation']]
      - ['addPermission', ['shopadmin', 'maywritetranslation']]
    tags: ['graphql_permissions_provider']
